### PR TITLE
enable ruff/RET and fixing `RET505` Unnecessary elif after return statement

### PR DESCRIPTION
**Pull request by Borda**
As it seems Ruff is well used, I may suggest also enabling RET simplification and also fixing all raised issues of _`RET505` Unnecessary elif after return statement_

### CODE REVIEW

**Comment by Borda** [comment]
I think that the codecov is a false alarm as we just reduced the number of lines os if any were not covered before, now they are just sending the wrong signal...

**Comment by Delgan** [comment]
Hi @Borda, thanks for suggesting additional rules and implementing the fixes!

Regarding the Codecov failure: Loguru aims for 100% code coverage, and I think we could and should add a new unit test to maintain this standard.

[One new line](https://github.com/Delgan/loguru/pull/1034/files#diff-acab8b47700c70707c332aba6b5e85925db903d112d5a148251ce791545d0d6cR27) was added but is not covered.

Would you mind adding an unit test in [this file](https://github.com/Delgan/loguru/blob/0f0cd6172a953e295fe941b65bb49d1649e46b4d/tests/test_defaults.py) such as `test_invalid_type()` for example, and ensuring the `env()` function returns `None` in this case?

On a second thought, I also think we shouldn't return `None` but raise an error instead:

```python
raise ValueError("The requested type '%r' is not supported" % type_)
```

**Comment by Borda** [comment]
@Delgan added Error + test

BTW, I think would be good to add a pattern for the message to be sure what exception you are receiving in a particular test...

**Comment by Delgan** [comment]
Thank you @Borda!

> BTW, I think it would be good to add a pattern for the message to be sure what exception you are receiving in a particular test... 🦩 could be enforced by ruff PT

Yes, I agree. Many tests were implemented at a time I wasn't aware of the `match` argument of `pytest.raises()`. Ideally, it should be fixed.

**Pull request merged**
