### PR TITLE
Add loguru-mypy to documentation

### LINKED ISSUE #277: Add documentation about the "loguru-mypy" plugin
See: https://github.com/kornicameister/loguru-mypy

This plugin could be referred in the documentation page about type hints: https://loguru.readthedocs.io/en/stable/api/type_hints.html

### PR DESCRIPTION
**Pull request by kornicameister**
Closes: #277 
Requires: https://github.com/pypa/pypi-support/issues/430 https://github.com/kornicameister/loguru-mypy/issues/19

### CODE REVIEW

**Comment by Delgan** [comment]
Hey @kornicameister, thanks for the PR.

A few notes:
* I prefer not the plugin to be installed using `loguru[mypy]`. It should be clear that `loguru-mypy` is a different package.
* I prefer that the installation part remains a very basic `pip install loguru`, that's part of the Readme design about "simplicity".
* Documentation should be added directly in the [`__init__.pyi`](https://github.com/Delgan/loguru/blob/8a0c0521c68c829bafb863e0c782020c0cbd00e1/loguru/__init__.pyi) file, it will be automatically generated by Sphinx.
* We could add a note about  the `mypy.ini` file and its content for those who don't know how to use `mypy` plugins.

People interested in type hinting will inevitably go to the corresponding page in the documentation, they will necessarily be aware of the existence of your `loguru-mypy` plugin.

**Comment by kornicameister** [comment]
@Delgan is that better :) ?

**Comment by Delgan** [comment]
Thank you @kornicameister, appreciate your understanding!

**Comment by kornicameister** [comment]
I just need pypi access restored 😥

**Comment by kornicameister** [comment]
Ok @Delgan first version of a plugin is already available here -> https://pypi.org/project/loguru-mypy/ :+1:

**Comment by Delgan** [comment]
That's really great, thanks a lot for your time @kornicameister! :heart:

**Pull request merged**
