### PR TITLE
add json log 

### PR DESCRIPTION
**Pull request by rxy007**
test:
image
result:
image

### CODE REVIEW

**Comment by Delgan** [comment]
Hi @rxy007, thank you for taking the time to do open a pull request. However,  there is already a similar attribute `serialize`, what would your new parameter do?

**Comment by rxy007** [comment]
hi, thank you for received you email. serialize is return all info, this is too mang and too long for me, i want return my need info. thank you again.


    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            xiaoyu.r
                            
                            
                                
                                    邮箱：xiaoyu.r@aliyun.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            On 01/22/2020 06:15, Delgan wrote: Hi @rxy007, thank you for taking the time to do open a pull request. However,  there is already a similar attribute serialize, what would your new parameter do?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Delgan/loguru/pull/205?email_source=notifications\u0026email_token=AFAZW6UNFFZZFP26D22RARLQ65XZBA5CNFSM4KJMJ5F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJRPHNA#issuecomment-576910260",
"url": "https://github.com/Delgan/loguru/pull/205?email_source=notifications\u0026email_token=AFAZW6UNFFZZFP26D22RARLQ65XZBA5CNFSM4KJMJ5F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJRPHNA#issuecomment-576910260",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Delgan** [comment]
@rxy007 Ok, thanks for the explanation. If the `serialize` attribute doesn't suit what you need, I think you should basically use a custom sink.  Here is an example of what you might use:

```python
def json_sink(message):
    record = message.record
    reduced = dict(
        time=record["time"],
        module=record["module"],
        level=record["level"].name,
        function=record["function"],
        line=record["line"],
        message=record["message"],
        extra=record["extra"],
    )
    serialized = json.dumps(reduced)
    print(serialized)

logger.add(json_sink)
```

However, I don't want to integrate such handler directly as a "built-in" to Loguru, because all users have different preferences.

**Comment by rxy007** [comment]
hi，thank you，you are right，if you example can run，i will try. thank you and 春节快乐


    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            xiaoyu.r
                            
                            
                                
                                    邮箱：xiaoyu.r@aliyun.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            On 01/23/2020 04:51, Delgan wrote: @rxy007 Ok, thanks for the explanation. If the serialize attribute doesn't suit what you need, I think you should basically use a custom sink.  Here is an example of what you might use:
def json_sink(message):
    record = message.record
    reduced = dict(
        time=record["time"],
        module=record["module"],
        level=record["level"].name,
        function=record["function"],
        line=record["line"],
        message=record["message"],
        extra=record["extra"],
    )
    serialized = json.dumps(reduced)
    print(serialized)

logger.add(json_sink)
However, I don't want to integrate such handler directly as a "built-in" to Loguru, because all users have different preferences.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Delgan/loguru/pull/205?email_source=notifications\u0026email_token=AFAZW6Q6C4RHWENFZRBCNBDQ7CWULA5CNFSM4KJMJ5F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJVBZOA#issuecomment-577379512",
"url": "https://github.com/Delgan/loguru/pull/205?email_source=notifications\u0026email_token=AFAZW6Q6C4RHWENFZRBCNBDQ7CWULA5CNFSM4KJMJ5F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJVBZOA#issuecomment-577379512",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
