### PR TITLE
Add recipe Implement RotatingFileHandler provided by logging package

### PR DESCRIPTION
**Pull request by k8uwall**
I wrote RotatingFileHandler using callable of retention.

It will be rotated like this
file.log file.log.1 file.log.2 file.log.3

### CODE REVIEW

**Comment by Delgan** [comment]
Hey @k8uwall, thanks for the PR! This is a good way to use a callable for `retention`.

Can you please briefly explain what are the advantages of using `Retentor` instead of `RotatingFileHandler`?

```python
handler = RotatingFileHandler("file.log", maxBytes=5000, backupCount=3)
logger.add(handler)
```

Also, I may be wrong, but shouldn't you call `os.remove()` somewhere to delete old log files?

**Comment by k8uwall** [comment]
Thank you for your answer.
Very good recipe for those who are thinking of switching from the default logging.
Why not put this in the README.md at the top?


It will be overwritten in this way, so there is no need to delete it in reverse.
```
cp file.log.2 file.log.3
cp file.log.1 file.log.2
cp file.2021-01-08_23-01-38_246557.log file.log.1
```

**Comment by Delgan** [comment]
> It will be overwritten in this way, so there is no need to delete it in reverse.

Oh, yeah, makes sense. Thanks.



> Thank you for your answer.
> Very good recipe for those who are thinking of switching from the default logging.
> Why not put this in the README.md at the top?

Well, I prefer to make the Readme focused on the use of Loguru and not on standard logging. But indeed, I think I could add the `RotatingFileHandler` in the documentation. Just before your recipe for example, or somewhere in the page about [migrating from standard logging](https://loguru.readthedocs.io/en/stable/resources/migration.html).

**Comment by k8uwall** [comment]
Thank you.
I'll send a pull request to the migration page next time.

**Pull request closed without merging**
