### PR TITLE
improve datetime perf

### PR DESCRIPTION
**Pull request by trim21**
benchmark with simple `logger.info("hello {}", "b")` with `os.devnull` sink, from 44s to 20s

ref: https://github.com/Delgan/loguru/issues/1201

### CODE REVIEW

**Comment by trim21** [comment]
... why are we still running tests on 3.5 and why we convert `[YYYY]` to `YYYY` in datetime formatting?

**Comment by trim21** [comment]
also， why aware_now use time module instead of using datetime.now.astimezone and combine it as datetime？

**Comment by trim21** [comment]
I think we can also include a fast path for default datetime format

**Comment by Delgan** [comment]
Hey @trim21.

Thank you for your work in improving Loguru's performance.
I never realized that `datetime` formatting was so costly. Good catch. Caching a pre-computed formatter is a simple and excellent idea to reduce the overhead.

I've done a few experiments and I think we can go even further. We do not need to repeatedly parse the tokens with the regex. We can build a formattable string associated with runtime formatting functions.

See the diff here: https://github.com/Delgan/loguru/commit/80f05fd2635a9f728565585fed02bed7c2be968a

Here are a `timeit` command using a non-default format:

```bash
$ python -m timeit -s "from loguru import logger;logger.remove();logger.add(lambda _: None, format='{time:YYYY-MM-DD HH:mm:ss.SSSSSS Z}');logger.info('Hello')" "for _ in range(10):logger.info('Hello')"
```

Results:

```bash
# master
500 loops, best of 5: 426 usec per loop

# trim21/datetime-perf
1000 loops, best of 5: 225 usec per loop

# Delgan/faster-datetime
2000 loops, best of 5: 160 usec per loop
```

It's arguably an almost negligible improvement on what you've already done, but it pushes optimization further without adding much complexity.

Do you mind if I merge this commit instead? Do you think it could be improved?

**Pull request closed without merging**
