### PR TITLE
Retention fix

### PR DESCRIPTION
**Pull request by gazpachoking**
Addresses issues in #195 

- Ensures directories are never deleted when handling retention
- Ensures log extension is included in filenames when handling retention

### CODE REVIEW

**Comment by gazpachoking** [comment]
Oops, should have run the tests locally before submitting. Requiring the dots was the one thing I knew could be made more specific, and is what's causing the failure right now. I was trying to avoid changing too much, I think to make it better we need multiple glob patterns.

**Comment by Delgan** [comment]
Thanks for the PR!
I guess it's just a small edge case, I fix is probably possible while keeping just one glob pattern. I will take a look.

**Comment by Delgan** [comment]
@gazpachoking Ok, you was totally right, multiple glob patterns are required. 

I took the liberty of making changes to your branch as a result of this PR, I hope you don't mind. 

While refactoring the code, I decided to combine the glob pattern with a regex check which I think is more permissive: we want to match `"file.2020-01-01_01-01-01_0000001.log"` (automatic renaming on rotation), but we want to exclude both `"file.foo.log"` and `"foo.file.log"` which is complicated without regex.

At the same time, I realized it was wrong to call `os.path.splitext()` after  `glob.escape()` as it would result in something like `("file\\", ".log")`, so I modified the corresponding code. 

Also, I tried to fix a 100%-theoretical bug that could occur if `"."` was present in the `{time}` spec format (leading to wrong `splitext()`).

This results in code much more convoluted unfortunately, but this should greatly reduce false positives during `retention` process. Does it look good to you?

**Comment by gazpachoking** [comment]
It is a bit hard to read and understand the glob and regex bit, but the expanded test suite is clear, and makes me confident it's doing what it's supposed to now. 👍

**Comment by Delgan** [comment]
Great, thanks for the review! Let's merge it then. ;)

**Pull request merged**
