### PR TITLE
fix: catch KeyError & ValueError when formatting failed

### PR DESCRIPTION
**Pull request by GreyElaina**

### CODE REVIEW

**Comment by GreyElaina** [comment]
as designed...

**Comment by crizCraig** [comment]
Why was this closed btw? Running into the same issue... #1008

**Comment by GreyElaina** [comment]
> Why was this closed btw? Running into the same issue... #1008

it donot fix this issue corrently.

**Comment by odevtmp** [comment]
pathetic. this library is not usable. how one is supposed to be sure beforehand that there will be no curlies in log messages? not everything depends on oneself

**Pull request closed without merging**
